services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    image: local/eorna2-httpd
    ports:
      - 9418:80
    volumes:
      - type: bind
        source: ./eorna2.conf
        target: /etc/httpd/conf.d/eorna2.conf
      - type: bind
        source: ../www/
        target: /var/www/
      - type: bind
        source: ../logs/
        target: /var/log/httpd/
    restart: unless-stopped
    container_name: eorna2-httpd

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: msZTg66954rJMAeL18mmQnSw
      MYSQL_DATABASE: eorna2
      MYSQL_USER: eorna2
      MYSQL_PASSWORD: eorna2
    ports:
      - 9422:3306
    volumes:
      - ../mysqldata:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - type: bind
        source: ../www/
        target: /var/www/
    restart: unless-stopped
    container_name: eorna2-mysql
